import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
       <div className='w-3/5 p-5'>Login Section </div>{/*Log in section*/}
       <div className="w-2/5 bg-green-500 text-white rounded-tr-2xl rounded-br-2xl py-36 px-12">{/*sign up section*/}
        <h2 className="text-3xl font-bold mb-2">Hello !</h2>
        <div className="border-2"></div>
        </div>
       </div>
      </main>

      
    </div>
  )
}
