import Head from 'next/head';
import Link from 'next/link';
import { FaFacebookF, FaLinkedinIn, FaGoogle, FaEnvelope, FaLock } from 'react-icons/fa';
import { useState } from 'react';
import axios from 'axios';
const url = "https://test.mshr.website/api/login";


export default function Home() {

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');


  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const res = await axios.post(url,
        {
          email,
          password,
        });
      console.log("reponse is : "+res.data);
    } catch (error) {
      console.log("error is "+error.response);
    }

  }
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">

          <div className='w-3/5 p-5'>

            <div className="text-left font-bold text-green-500">
              MAJOR
            </div>

            <div className="py-10">
              <h2 className="text-3xl text-green-500 font-bold mb-2">Sign in to Account</h2>
              <div className="border-2 w-10 border-green-500 inline-block mb-2 "></div>

              <div className="flex justify-center my-2">{/* social login section */}
                <a href="#" className="border-2 border-gray-200 rounded-full p-3 mx-1">
                  <FaFacebookF className='text-sm' />
                </a>
                <a href="#" className="border-2 border-gray-200 rounded-full p-3 mx-1">
                  <FaGoogle className='text-sm' />
                </a>
                <a href="#" className="border-2 border-gray-200 rounded-full p-3 mx-1">
                  <FaLinkedinIn className='text-sm' />
                </a>
              </div>

              <p className="text-gray-400 my-3"> or use your email account </p>

              <form onSubmit={handleSubmit}>
                <div className="flex flex-col items-center ">
                  <div className="p-2 bg-gray-100 w-64 flex items-center mb-3">
                    <FaEnvelope className="text-gray-400 m-2" />
                    <input type="email"
                      placeholder="Email"
                      className=" flex-1 outline-none bg-gray-100 text-sm"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                    />
                  </div>
                  <div className="p-2 bg-gray-100 w-64 flex items-center mb-3">
                    <FaLock className="text-gray-400 m-2" />
                    <input type="password"
                      placeholder="Password"
                      className=" flex-1 outline-none bg-gray-100 text-sm"
                    value={password}
                    onChange={(e)=>setPassword(e.target.value)}
                    />
                  </div>
                  <div className="flex justify-between w-64 mb-5">
                    <label className="flex items-center text-xs">
                      <input type="checkbox" name="remember" className="mr-1" />Remember me
                    </label>
                    <a href="#" className="text-xs">Forgot Password?</a>
                  </div>

                  <div className=" px-12 py-2 inline-block bg-green-500 border-2 border-white rounded-full font-semibold hover:bg-green-700 hover:border-gray-300 hover:shadow-2xl" >
                    <button>Log In</button>
                  </div>

                </div>
              </form>
            </div>
          </div>



          <div className="w-2/5 bg-green-500 text-white rounded-tr-2xl rounded-br-2xl py-36 px-12">{/*sign up section*/}
            <h2 className="text-3xl font-bold mb-2">Hello !</h2>
            <div className="border-2 w-10 border-white inline-block mb-2 "></div>
            <p className="mb-10">Fill up and start the journey!</p>
            <p className=" px-12 py-2 inline-block border-2 border-white rounded-full font-semibold hover:bg-green-700 hover:border-gray-300 hover:shadow-2xl" >
              <Link href="/components/SignUpPage">Sign Up</Link>
            </p>
          </div>
        </div>
      </main>


    </div>
  )
}
