import React from 'react';
import Head from 'next/head';
import axios from 'axios';
import { useState } from 'react';

const url = "https://test.mshr.website/api/register";

const SignUpPage = () => {

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();

    
     axios.post(url, { email, password }).then(function(res){
      console.log("reponse is : " + res.message);
     }).catch (function(error) {
     console.log("error is " + error.message);
    });
    

  }
  
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-100">
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="bg-white rounded-2xl shadow-2xl flex w-1/3 max-w-4xl">

          <div className="p-5">

            <div className="text-left font-bold text-green-500">
              MAJOR
            </div>

            <div className="py-10 px-12 ">
              <h2 className="text-3xl text-green-500 font-bold mb-2">Sign Up</h2>
              <div className="border-2 w-10 border-green-500 inline-block mb-2 "></div>




              <form className='form' onSubmit={handleSubmit}>
                <div className="flex flex-col items-center ">

                  <div className="p-2 bg-gray-100 w-64 flex items-center mb-3">

                    <input
                      type="text"
                      placeholder="Name"
                      className=" flex-1 outline-none bg-gray-100 text-sm"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                    />
                  </div>
                  <div className="p-2 bg-gray-100 w-64 flex items-center mb-3">

                    <input type="email"
                      placeholder="Email"
                      className=" flex-1 outline-none bg-gray-100 text-sm"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                    />
                  </div>
                  <div className="p-2 bg-gray-100 w-64 flex items-center mb-3">

                    <input type="password"
                      placeholder="Password"
                      className=" flex-1 outline-none bg-gray-100 text-sm"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                    />
                  </div>


                  <div className=" px-12 py-2 inline-block bg-green-500 border-2 border-white rounded-full font-semibold hover:bg-green-700 hover:border-gray-300 hover:shadow-2xl" >
                    <button >Register</button>
                  </div>

                </div>
              </form>
            </div>
          </div>

        </div>
      </main>


    </div>
  )
}

export default SignUpPage